[project]
name = "llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "huggingface>=0.0.1",
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1",
    "torch>=2.8.0",
    "transformers>=4.55.3",
]
